import React, { useRef, useState, useEffect } from 'react';
import { X, Printer, Download, Sparkles } from 'lucide-react';
import { prescriptionAPI, certificateAPI, consentAPI, clinicAPI } from '../services/api';
import { useClinic } from '../context/ClinicContext';

function formatDate(date) {
  if (!date) return '';
  try {
    const d = new Date(date);
    if (isNaN(d.getTime())) return String(date);
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const day = String(d.getDate()).padStart(2, '0');
    const month = months[d.getMonth()];
    const year = d.getFullYear();
    return `${day} ${month} ${year}`;
  } catch (_) {
    return String(date);
  }
}

function calculateAge(dob) {
  if (!dob) return '';
  try {
    const birthDate = new Date(dob);
    if (isNaN(birthDate.getTime())) return '';
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    return age > 0 ? String(age) : '';
  } catch (_) {
    return '';
  }
}

export default function PdfPreviewModal({
  isOpen,
  onClose,
  type = 'prescription', // 'prescription' | 'certificate' | 'instruction' | 'consent'
  data = {},
  patient = {},
  clinic = {},
  doctor = {}
}) {
  const printRef = useRef(null);
  const [downloadingServerPdf, setDownloadingServerPdf] = useState(false);
  const clinicCtx = useClinic();

  // Resolve Clinic & Template
  const resolvedClinic = (clinic && (clinic.name || clinic._id))
    ? clinic
    : (data.clinic_id && typeof data.clinic_id === 'object' ? data.clinic_id : (clinicCtx?.currentClinic || {}));

  const initialTemplate = resolvedClinic?.pdf_template || {};
  const [liveTemplate, setLiveTemplate] = useState(initialTemplate);

  // Sync latest template from backend whenever modal opens
  useEffect(() => {
    if (!isOpen) return;
    const cid = resolvedClinic?._id || clinic?._id || clinic?.id || data?.clinic_id?._id || data?.clinic_id || clinicCtx?.selectedClinicId;
    if (cid && cid !== 'all') {
      clinicAPI.getPdfTemplate(cid)
        .then((res) => {
          if (res?.success && res?.data) {
            setLiveTemplate(res.data);
          }
        })
        .catch(() => {});
    }
  }, [isOpen, resolvedClinic?._id, clinic, data, clinicCtx?.selectedClinicId]);

  if (!isOpen) return null;

  const activeTemplate = liveTemplate || initialTemplate;
  const headerMode = activeTemplate.header_mode || 'digital';
  const headerMarginMm = Number(activeTemplate.header_margin_mm) || 50;
  const primaryColor = activeTemplate.primary_color || '#0F766E';

  const showDate = activeTemplate.show_date !== false;
  const customDate = activeTemplate.custom_date ? String(activeTemplate.custom_date).trim() : '';
  const showVitals = activeTemplate.show_vitals !== false;
  const showDiagnosis = activeTemplate.show_diagnosis !== false;
  const showAdvice = activeTemplate.show_advice !== false;
  const showPatientAddress = activeTemplate.show_patient_address !== false;
  const showPatientPhone = activeTemplate.show_patient_phone !== false;
  const showNextVisit = activeTemplate.show_next_visit !== false;
  const showSignature = activeTemplate.show_signature !== false;
  const showStamp = activeTemplate.show_stamp !== false;
  const showFooter = activeTemplate.show_footer !== false;
  const footerText = activeTemplate.footer_text || 'Generated by Adixon Clinic OS';

  const resolveAsset = (asset) => {
    if (!asset) return '';
    if (typeof asset === 'string') return asset.trim();
    if (typeof asset === 'object') return asset.secure_url || asset.url || '';
    return '';
  };

  // Resolve Doctor (Real data from doctor prop or populated data.doctor_id or resolvedClinic)
  const resolvedDoctor = (doctor && (doctor.full_name || doctor.name || doctor._id))
    ? doctor
    : (data.doctor_id && typeof data.doctor_id === 'object' ? data.doctor_id : {});

  const doctorName = resolvedDoctor.full_name || resolvedDoctor.name || resolvedClinic.doctor_name || 'Doctor';
  const doctorQualification = resolvedDoctor.qualification || resolvedClinic.doctor_qualification || 'MBBS';
  const doctorReg = resolvedDoctor.registration_number || resolvedClinic.registration_number || '';
  const signatureUrl = resolvedDoctor.signature_url || resolveAsset(resolvedDoctor.signature) || resolveAsset(resolvedClinic.doctor_signature) || resolvedClinic.doctor_signature_url || '';

  // Resolve Patient (Real data from patient prop or populated data.patient_id or data fields)
  const resolvedPatient = (patient && (patient.full_name || patient.name || patient._id))
    ? patient
    : (data.patient_id && typeof data.patient_id === 'object' ? data.patient_id : {});

  const patientName = resolvedPatient.full_name || resolvedPatient.name || data.patient_name || 'Patient';
  const patientGender = resolvedPatient.gender || data.patient_gender || '';
  const patientAge = resolvedPatient.age || (resolvedPatient.dob ? calculateAge(resolvedPatient.dob) : '') || data.patient_age || '';
  const patientAddress = resolvedPatient.address || data.patient_address || '';
  const patientPhone = resolvedPatient.phone || data.patient_phone || '';

  let genderAgeStr = '';
  if (patientGender && patientAge) {
    genderAgeStr = `, ${patientGender} / ${patientAge} Yrs`;
  } else if (patientGender) {
    genderAgeStr = `, ${patientGender}`;
  } else if (patientAge) {
    genderAgeStr = ` / ${patientAge} Yrs`;
  }

  // Resolve Clinic Info (Real data from clinic or clinicCtx)
  const clinicName = resolvedClinic.name || resolvedClinic.clinicName || 'Clinic';
  const clinicAddress = resolvedClinic.address || '';
  const clinicPhone = resolvedClinic.phone || '';
  const clinicEmail = resolvedClinic.email || '';

  const logoUrl = resolvedClinic.logo_url || resolvedClinic.logoUrl || resolveAsset(resolvedClinic.logo) || resolveAsset(resolvedClinic.profile_url) || '/adixon-logo.png';
  const stampUrl = resolveAsset(resolvedClinic.stamp) || resolvedClinic.stamp_url || resolvedClinic.stampUrl || '';

  const visitDate = formatDate(data.visit_date || data.createdAt);
  const issueDate = formatDate(data.issue_date || data.createdAt);
  const dateToShow = customDate || issueDate || visitDate || formatDate(new Date());

  // Vitals
  const vitals = data.vitals || {};
  const vitalsList = [];
  if (showVitals) {
    if (vitals.temperature) vitalsList.push({ label: 'Temperature', val: `${vitals.temperature} ° F` });
    if (vitals.height) vitalsList.push({ label: 'Height', val: `${vitals.height} cm` });
    if (vitals.weight) vitalsList.push({ label: 'Weight', val: `${vitals.weight} kg` });
    if (vitals.pulse_rate) vitalsList.push({ label: 'Pulse', val: `${vitals.pulse_rate} bpm` });
    if (vitals.blood_pressure) vitalsList.push({ label: 'BP', val: vitals.blood_pressure });
    if (vitals.blood_sugar) vitalsList.push({ label: 'Blood Sugar', val: `${vitals.blood_sugar} mg/dL` });
    if (vitals.hemoglobin) vitalsList.push({ label: 'Hemoglobin', val: `${vitals.hemoglobin} g/dL` });
    if (vitals.spo2) vitalsList.push({ label: 'SpO2', val: `${vitals.spo2} %` });
    if (vitals.respiration_rate) vitalsList.push({ label: 'Respiration Rate', val: `${vitals.respiration_rate} /min` });
  }

  // Clinical Details
  const clinical = data.clinical || {};
  const clinicalNotes = [];
  if (clinical.allergy) clinicalNotes.push({ label: 'Allergies', val: clinical.allergy });
  if (clinical.chief_complaint) clinicalNotes.push({ label: 'Chief Complaint', val: clinical.chief_complaint });
  if (clinical.patient_history) clinicalNotes.push({ label: 'History', val: clinical.patient_history });
  if (clinical.findings) clinicalNotes.push({ label: 'Findings', val: clinical.findings });
  if (clinical.treatment) clinicalNotes.push({ label: 'Treatment/Advice', val: clinical.treatment });
  if (clinical.notes) clinicalNotes.push({ label: 'End Note', val: clinical.notes });

  const diagnosis = clinical.diagnosis || data.diagnosis || '';
  const labs = data.labs || [];
  const medicines = data.medicines || [];

  // Follow-up Date formatting for Next Visit
  const followUpDate = data.follow_up_date 
    ? formatDate(data.follow_up_date)
    : (data.clinical?.follow_up_date ? formatDate(data.clinical.follow_up_date) : '');
  const followUpTime = data.clinical?.follow_up_time || '';
  const followUpPurpose = data.clinical?.follow_up_purpose || '';
  let followUpText = '';
  if (followUpDate) {
    followUpText = `Next Visit: ${followUpDate}`;
    if (followUpTime) followUpText += ` at ${followUpTime}`;
    if (followUpPurpose) followUpText += ` - ${followUpPurpose}`;
  }

  const handleDownloadServerPdf = async () => {
    if (!data._id) return;
    try {
      setDownloadingServerPdf(true);
      let blob;
      let filePrefix = 'Prescription';
      if (type === 'certificate') {
        blob = await certificateAPI.getPdfBlob(data._id);
        filePrefix = 'Certificate';
      } else if (type === 'consent') {
        blob = await consentAPI.getPdfBlob(data._id);
        filePrefix = 'Consent';
      } else {
        blob = await prescriptionAPI.getPdfBlob(data._id);
      }
      const url = window.URL.createObjectURL(new Blob([blob], { type: 'application/pdf' }));
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filePrefix}_${(patientName || 'Patient').replace(/\s+/g, '_')}_${data._id}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error('Failed to download server PDF:', err);
      handlePrint();
    } finally {
      setDownloadingServerPdf(false);
    }
  };

  const handlePrint = () => {
    const printContent = printRef.current.innerHTML;
    const printWindow = window.open('', '_blank', 'width=900,height=1000');
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${type.toUpperCase()} - ${patientName}</title>
          <style>
            @page {
              size: A4;
              margin: 12mm 16mm 14mm 16mm;
            }
            * {
              box-sizing: border-box;
              margin: 0;
              padding: 0;
            }
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
              color: #0F172A;
              margin: 0;
              padding: 0;
              background: #fff;
              -webkit-print-color-adjust: exact !important;
              print-color-adjust: exact !important;
              font-size: 11px;
              line-height: 1.45;
            }
            .pdf-container {
              width: 100%;
              max-width: 800px;
              margin: 0 auto;
              box-sizing: border-box;
            }
            .letterhead-placeholder {
              display: block !important;
              height: ${headerMarginMm}mm !important;
              min-height: ${headerMarginMm}mm !important;
              border: none !important;
              background: transparent !important;
              color: transparent !important;
            }
            @media print {
              .no-print { display: none !important; }
              .letterhead-placeholder {
                border: none !important;
                background: transparent !important;
                color: transparent !important;
              }
            }
          </style>
        </head>
        <body>
          <div class="pdf-container">
            ${printContent}
          </div>
          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="right-drawer-backdrop" onClick={onClose} style={{ zIndex: 1000 }}>
      <div 
        className="card" 
        onClick={(e) => e.stopPropagation()} 
        style={{ 
          maxWidth: '850px', 
          width: '92%', 
          maxHeight: '94vh', 
          display: 'flex', 
          flexDirection: 'column', 
          borderRadius: '16px',
          overflow: 'hidden',
          padding: 0
        }}
      >
        {/* Header Action Bar */}
        <div style={{ padding: '14px 20px', background: 'var(--color-bg-secondary)', borderBottom: '1px solid var(--color-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Sparkles size={18} color={primaryColor} />
            <h3 style={{ fontSize: '15px', fontWeight: 'bold', margin: 0 }}>
              PDF Print Preview ({type.charAt(0).toUpperCase() + type.slice(1)})
            </h3>
            {headerMode === 'letterhead' && (
              <span className="badge badge-warning" style={{ fontSize: '11px', padding: '2px 8px' }}>
                Letterhead Pad ({headerMarginMm}mm)
              </span>
            )}
          </div>
          <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
            {data._id && (
              <button 
                className="btn btn-secondary" 
                onClick={handleDownloadServerPdf}
                disabled={downloadingServerPdf}
                style={{ padding: '6px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <Download size={15} /> {downloadingServerPdf ? 'Generating...' : 'Server PDF'}
              </button>
            )}
            <button className="btn btn-primary" onClick={handlePrint} style={{ backgroundColor: primaryColor, borderColor: primaryColor, padding: '6px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Printer size={15} /> Print / Save PDF
            </button>
            <button className="icon-btn" onClick={onClose}>
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Scrollable Document Container */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '24px', background: '#525659', display: 'flex', justifyContent: 'center' }}>
          {/* Paper A4 Container (Identical to Puppeteer PDF Layout) */}
          <div 
            ref={printRef}
            style={{ 
              width: '100%', 
              maxWidth: '720px', 
              minHeight: '920px', 
              background: '#FFFFFF', 
              padding: '28px 32px', 
              boxShadow: '0 8px 30px rgba(0,0,0,0.3)', 
              borderRadius: '2px',
              fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
              color: '#0F172A',
              boxSizing: 'border-box',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
              fontSize: '11px',
              lineHeight: 1.45
            }}
          >
            <div>
              {/* TOP HEADER SECTION (Digital vs Letterhead Mode) */}
              {headerMode === 'letterhead' ? (
                <div 
                  className="letterhead-placeholder"
                  style={{
                    height: `${headerMarginMm * 3.78}px`,
                    minHeight: `${headerMarginMm * 3.78}px`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: '#94A3B8',
                    fontSize: '11px',
                    marginBottom: '16px',
                    background: '#F8FAFC',
                    border: '1px dashed #CBD5E1',
                    borderRadius: '4px'
                  }}
                >
                  Pre-Printed Letterhead Reserved Space ({headerMarginMm} mm)
                </div>
              ) : (
                <div style={{ 
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'flex-start',
                  borderBottom: '1.5px solid #E2E8F0',
                  paddingBottom: '12px',
                  marginBottom: '14px'
                }}>
                  {/* Doctor Info (Left) */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                    {logoUrl ? (
                      <img src={logoUrl} alt="Clinic Logo" style={{ width: '72px', height: '72px', borderRadius: '10px', objectFit: 'contain' }} />
                    ) : (
                      <div style={{ width: '72px', height: '72px', background: primaryColor, color: '#fff', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '14px' }}>
                        Dr
                      </div>
                    )}
                    <div>
                      <h2 style={{ fontSize: '16px', fontWeight: '700', margin: '0 0 2px', color: '#0F172A' }}>
                        {doctorName.startsWith('Dr.') ? doctorName : `Dr. ${doctorName}`}
                      </h2>
                      {doctorQualification && (
                        <div style={{ fontSize: '11px', color: '#475569', marginBottom: '2px' }}>{doctorQualification}</div>
                      )}
                      {doctorReg && (
                        <div style={{ fontSize: '10px', color: primaryColor }}>
                          Reg. No: <u>{doctorReg}</u>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Clinic Info (Right) */}
                  <div style={{ textAlign: 'right', fontSize: '10px', color: '#475569', lineHeight: '1.4' }}>
                    <div style={{ fontSize: '13px', fontWeight: '700', color: '#0F172A', marginBottom: '2px' }}>{clinicName}</div>
                    {clinicAddress && <div>{clinicAddress}</div>}
                    {clinicPhone && <div>Contact: {clinicPhone}</div>}
                    {clinicEmail && <div>Mail: {clinicEmail}</div>}
                  </div>
                </div>
              )}

              {/* PATIENT BANNER (Clean, Centered, No box) */}
              <div style={{ 
                textAlign: 'center', 
                fontSize: '12px', 
                color: '#475569', 
                marginBottom: '16px',
                padding: '4px 0'
              }}>
                Patient : <strong style={{ color: '#0F172A', fontSize: '13px' }}>{patientName}{genderAgeStr}</strong>
              </div>

              {/* 1. PRESCRIPTION BODY */}
              {type === 'prescription' && (
                <div>
                  <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start' }}>
                    {/* Left Column (flex: 1.05) */}
                    <div style={{ flex: 1.05, paddingRight: '8px' }}>
                      {showDate && (
                        <div style={{ fontSize: '11px', marginBottom: '5px', color: '#0F172A', fontWeight: '600' }}>
                          Date : {dateToShow}
                        </div>
                      )}

                      {showPatientAddress && patientAddress && (
                        <div style={{ fontSize: '11px', marginBottom: '5px', color: '#0F172A' }}>
                          Address : {patientAddress}
                        </div>
                      )}

                      {showPatientPhone && patientPhone && (
                        <div style={{ fontSize: '11px', marginBottom: '5px', color: '#0F172A' }}>
                          Phone : {patientPhone}
                        </div>
                      )}

                      {/* Vitals */}
                      {showVitals && vitalsList.length > 0 && (
                        <div style={{ marginTop: '6px' }}>
                          {vitalsList.map((v, idx) => (
                            <div key={idx} style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}>
                              <span style={{ fontWeight: '500' }}>{v.label} :</span> <span>{v.val}</span>
                            </div>
                          ))}
                        </div>
                      )}

                      {/* Clinical Details */}
                      {clinicalNotes.length > 0 && (
                        <div style={{ marginTop: '8px' }}>
                          {clinicalNotes.map((c, idx) => (
                            <div key={idx} style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}>
                              <span style={{ fontWeight: '500' }}>{c.label} :</span> <span>{c.val}</span>
                            </div>
                          ))}
                        </div>
                      )}

                      {/* Diagnosis */}
                      {showDiagnosis && diagnosis && (
                        <div style={{ marginTop: '10px', marginBottom: '12px', fontSize: '12px', fontWeight: '700', color: '#0F172A' }}>
                          Diagnosis : {diagnosis}
                        </div>
                      )}

                      {/* Advice / Labs */}
                      {showAdvice && labs.length > 0 && (
                        <div style={{ marginTop: '14px' }}>
                          <div style={{ fontSize: '13px', fontWeight: '700', color: primaryColor, marginBottom: '6px' }}>
                            Advice
                          </div>
                          {labs.map((l, idx) => (
                            <div key={idx} style={{ fontSize: '10.5px', color: '#1E293B', marginBottom: '4px', paddingLeft: '4px' }}>
                              - {typeof l === 'string' ? l : (l.name || l.lab_test)}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>

                    {/* Right Column (flex: 1.35) */}
                    <div style={{ flex: 1.35 }}>
                      <div style={{ fontSize: '18px', fontWeight: '800', color: primaryColor, marginBottom: '14px', letterSpacing: '0.5px' }}>
                        Rx
                      </div>

                      {medicines && medicines.length > 0 ? (
                        medicines.map((m, idx) => {
                          const qtyStr = m.quantity ? ` (Qty: ${m.quantity})` : '';
                          const details = [
                            m.frequency,
                            m.instruction,
                            m.no_of_days ? `for ${m.no_of_days} Days` : '',
                            m.route ? `(Route: ${m.route})` : '',
                          ].filter(Boolean).join(' ');

                          return (
                            <div key={idx} style={{ marginBottom: '14px' }}>
                              <div style={{ fontSize: '12px', fontWeight: '700', color: '#0F172A', marginBottom: '3px' }}>
                                {m.name}{qtyStr}
                              </div>
                              {details && (
                                <div style={{ fontSize: '10.5px', color: '#334155', marginBottom: '2px' }}>
                                  {details}
                                </div>
                              )}
                              {m.additional_comments && (
                                <div style={{ fontSize: '10px', color: '#64748B', fontStyle: 'italic' }}>
                                  Note: {m.additional_comments}
                                </div>
                              )}
                            </div>
                          );
                        })
                      ) : (
                        <div style={{ color: '#94A3B8', fontStyle: 'italic' }}>No medicines prescribed</div>
                      )}
                    </div>
                  </div>

                  {/* Next Visit */}
                  {showNextVisit && followUpText && (
                    <div style={{ marginTop: '24px', marginBottom: '20px', fontSize: '11.5px', fontWeight: '700', color: '#0F172A' }}>
                      {followUpText}
                    </div>
                  )}
                </div>
              )}

              {/* 2. CERTIFICATE BODY */}
              {type === 'certificate' && (
                <div style={{ fontSize: '12px', lineHeight: '1.8', color: '#0F172A', marginTop: '16px' }}>
                  <div style={{ textAlign: 'center', marginBottom: '20px' }}>
                    <h2 style={{ fontSize: '15px', fontWeight: '700', color: primaryColor, textTransform: 'uppercase', letterSpacing: '1px', margin: 0 }}>
                      {data.certificate_type || 'MEDICAL CERTIFICATE'}
                    </h2>
                  </div>

                  {showDate && (
                    <div style={{ fontSize: '11px', marginBottom: '8px', color: '#0F172A', fontWeight: '600' }}>
                      Date : {dateToShow}
                    </div>
                  )}

                  {data.duration && (
                    <div style={{ marginBottom: '14px', background: '#F1F5F9', padding: '6px 12px', borderRadius: '4px', fontWeight: 'bold', display: 'inline-block' }}>
                      Duration / Leave : {data.duration}
                    </div>
                  )}

                  <div style={{ whiteSpace: 'pre-wrap', marginBottom: '20px' }}>
                    {data.content || 'This is to certify that the patient was examined at our clinic and advised recovery rest.'}
                  </div>

                  {data.remark && (
                    <div style={{ marginTop: '16px', borderLeft: `3px solid ${primaryColor}`, paddingLeft: '10px', fontStyle: 'italic', color: '#475569' }}>
                      <strong>Remarks :</strong> {data.remark}
                    </div>
                  )}
                </div>
              )}

              {/* 3. INSTRUCTION BODY */}
              {type === 'instruction' && (
                <div style={{ fontSize: '12px', lineHeight: '1.8', color: '#0F172A', marginTop: '16px' }}>
                  <div style={{ textAlign: 'center', marginBottom: '20px' }}>
                    <h2 style={{ fontSize: '15px', fontWeight: '700', color: primaryColor, textTransform: 'uppercase', letterSpacing: '1px', margin: 0 }}>
                      {data.title || 'PATIENT INSTRUCTION'}
                    </h2>
                  </div>
                  <div style={{ whiteSpace: 'pre-wrap' }}>
                    {data.description || data.content || 'Please follow all medical guidelines as instructed.'}
                  </div>
                </div>
              )}

              {/* 4. CONSENT BODY */}
              {type === 'consent' && (
                <div style={{ fontSize: '12px', lineHeight: '1.75', color: '#0F172A', marginTop: '16px' }}>
                  <div style={{ textAlign: 'center', marginBottom: '20px' }}>
                    <h2 style={{ fontSize: '15px', fontWeight: '700', color: primaryColor, textTransform: 'uppercase', letterSpacing: '1px', margin: 0 }}>
                      {data.title || 'PATIENT PROCEDURE CONSENT'}
                    </h2>
                  </div>

                  <div style={{ whiteSpace: 'pre-wrap', marginBottom: '30px' }}>
                    {data.content || 'I hereby give full consent to the medical procedure and treatment as explained by the practitioner.'}
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: '40px' }}>
                    {/* Patient Signature */}
                    <div style={{ border: '1px solid #CBD5E1', padding: '10px 14px', borderRadius: '6px', minWidth: '170px', textAlign: 'center' }}>
                      {data.patient_signature && (data.patient_signature.startsWith('http') || data.patient_signature.startsWith('data:')) ? (
                        <img src={data.patient_signature} alt="Patient Sig" style={{ height: '36px', objectFit: 'contain' }} />
                      ) : data.patient_signature ? (
                        <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Brush Script MT', cursive, serif", fontSize: '18px', fontStyle: 'italic', color: '#0F172A' }}>
                          {data.patient_signature}
                        </div>
                      ) : (
                        <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#94A3B8', fontSize: '10px' }}>Signature</div>
                      )}
                      <div style={{ borderTop: '1px solid #94A3B8', marginTop: '6px', paddingTop: '4px', fontSize: '10px', fontWeight: 'bold' }}>
                        Patient / Guardian Signature
                      </div>
                      <div style={{ fontSize: '9px', color: '#64748B' }}>{patientName}</div>
                    </div>

                    {/* Stamp */}
                    {showStamp && stampUrl && (
                      <div style={{ textAlign: 'center' }}>
                        <img src={stampUrl} alt="Stamp" style={{ width: '75px', height: '75px', objectFit: 'contain' }} />
                      </div>
                    )}

                    {/* Doctor Signature */}
                    <div style={{ border: '1px solid #CBD5E1', padding: '10px 14px', borderRadius: '6px', minWidth: '170px', textAlign: 'center' }}>
                      {showSignature && signatureUrl ? (
                        <img src={signatureUrl} alt="Doctor Sig" style={{ height: '36px', objectFit: 'contain' }} />
                      ) : showSignature && data.doctor_signature ? (
                        <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Brush Script MT', cursive, serif", fontSize: '18px', fontStyle: 'italic', color: '#0F172A' }}>
                          {data.doctor_signature}
                        </div>
                      ) : (
                        <div style={{ height: '36px' }} />
                      )}
                      <div style={{ borderTop: '1px solid #94A3B8', marginTop: '6px', paddingTop: '4px', fontSize: '10px', fontWeight: 'bold' }}>
                        Doctor Witness Signature
                      </div>
                      <div style={{ fontSize: '9px', color: '#64748B' }}>Dr. {doctorName}</div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* BOTTOM SECTION: Stamp, Signature & Footer Strip (For Prescription & Certificate) */}
            {type !== 'consent' && (
              <div style={{ marginTop: 'auto', paddingTop: '20px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '16px' }}>
                  {/* Stamp */}
                  <div style={{ width: '90px', height: '90px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    {showStamp && stampUrl && (
                      <img src={stampUrl} alt="Stamp" style={{ maxWidth: '90px', maxHeight: '90px', objectFit: 'contain' }} />
                    )}
                  </div>

                  {/* Signature */}
                  {showSignature && (
                    <div style={{ textAlign: 'center', minWidth: '150px' }}>
                      {signatureUrl ? (
                        <img src={signatureUrl} alt="Doctor Signature" style={{ maxWidth: '130px', maxHeight: '48px', objectFit: 'contain', marginBottom: '4px' }} />
                      ) : (
                        <div style={{ height: '36px' }} />
                      )}
                      <div style={{ width: '140px', height: '1px', background: '#64748B', margin: '0 auto 4px auto' }} />
                      <div style={{ fontSize: '11.5px', fontWeight: '700', color: '#0F172A' }}>
                        Dr. {doctorName}
                      </div>
                      {doctorQualification && <div style={{ fontSize: '10px', color: '#64748B' }}>{doctorQualification}</div>}
                    </div>
                  )}
                </div>

                {/* Footer Strip */}
                {showFooter && (
                  <div style={{
                    background: '#F1F5F9',
                    padding: '7px 12px',
                    borderRadius: '4px',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    fontSize: '9.5px',
                    color: '#475569'
                  }}>
                    <div>{clinicName} {clinicPhone}</div>
                    <div>{footerText}</div>
                  </div>
                )}
              </div>
            )}

            {/* CONSENT FOOTER BAR */}
            {type === 'consent' && showFooter && (
              <div style={{
                marginTop: 'auto',
                paddingTop: '20px'
              }}>
                <div style={{
                  background: '#F1F5F9',
                  padding: '7px 12px',
                  borderRadius: '4px',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  fontSize: '9.5px',
                  color: '#475569'
                }}>
                  <div>{clinicName} {clinicPhone}</div>
                  <div>{footerText}</div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
