import React, { useRef, useState, useEffect } from 'react';
import { X, Printer, Download, Sparkles } from 'lucide-react';
import { prescriptionAPI, certificateAPI, consentAPI, clinicAPI } from '../services/api';
import { useClinic } from '../context/ClinicContext';

function calculateAge(dob) {
  if (!dob) return '';
  try {
    const birthDate = new Date(dob);
    if (isNaN(birthDate.getTime())) return '';
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    return age > 0 ? String(age) : '';
  } catch (_) {
    return '';
  }
}

export default function PdfPreviewModal({
  isOpen,
  onClose,
  type = 'prescription', // 'prescription' | 'certificate' | 'instruction' | 'consent'
  data = {},
  patient = {},
  clinic = {},
  doctor = {}
}) {
  const printRef = useRef(null);
  const [downloadingServerPdf, setDownloadingServerPdf] = useState(false);
  const clinicCtx = useClinic();

  // Resolve Clinic & Template
  const resolvedClinic = (clinic && (clinic.name || clinic._id))
    ? clinic
    : (data.clinic_id && typeof data.clinic_id === 'object' ? data.clinic_id : (clinicCtx?.currentClinic || {}));

  const initialTemplate = resolvedClinic?.pdf_template || {};
  const [liveTemplate, setLiveTemplate] = useState(initialTemplate);

  // Sync latest template from backend whenever modal opens
  useEffect(() => {
    if (!isOpen) return;
    const cid = resolvedClinic?._id || clinic?._id || clinic?.id || data?.clinic_id?._id || data?.clinic_id || clinicCtx?.selectedClinicId;
    if (cid && cid !== 'all') {
      clinicAPI.getPdfTemplate(cid)
        .then((res) => {
          if (res?.success && res?.data) {
            setLiveTemplate(res.data);
          }
        })
        .catch(() => { });
    }
  }, [isOpen, resolvedClinic?._id, clinic, data, clinicCtx?.selectedClinicId]);

  if (!isOpen) return null;

  const activeTemplate = liveTemplate || initialTemplate;
  const headerMode = activeTemplate.header_mode || 'digital';
  const headerMarginMm = Number(activeTemplate.header_margin_mm) || 50;
  const primaryColor = activeTemplate.primary_color || '#0F766E';

  const showVitals = activeTemplate.show_vitals !== false;
  const showDiagnosis = activeTemplate.show_diagnosis !== false;
  const showAdvice = activeTemplate.show_advice !== false;
  const showPatientAddress = activeTemplate.show_patient_address !== false;
  const showPatientPhone = activeTemplate.show_patient_phone !== false;
  const showNextVisit = activeTemplate.show_next_visit !== false;
  const showSignature = activeTemplate.show_signature !== false;
  const showStamp = activeTemplate.show_stamp !== false;
  const showFooter = activeTemplate.show_footer !== false;
  const footerText = activeTemplate.footer_text || 'Generated by Adixon Clinic OS';

  const resolveAsset = (asset) => {
    if (!asset) return '';
    if (typeof asset === 'string') return asset.trim();
    if (typeof asset === 'object') return asset.secure_url || asset.url || '';
    return '';
  };

  // Resolve Doctor (Real data from doctor prop or populated data.doctor_id or resolvedClinic)
  const resolvedDoctor = (doctor && (doctor.full_name || doctor.name || doctor._id))
    ? doctor
    : (data.doctor_id && typeof data.doctor_id === 'object' ? data.doctor_id : {});

  const doctorName = resolvedDoctor.full_name || resolvedDoctor.name || resolvedClinic.doctor_name || '';
  const doctorQualification = resolvedDoctor.qualification || resolvedClinic.doctor_qualification || '';
  const doctorReg = resolvedDoctor.registration_number || resolvedClinic.registration_number || '';
  const signatureUrl = resolvedDoctor.signature_url || resolveAsset(resolvedDoctor.signature) || resolveAsset(resolvedClinic.doctor_signature) || resolvedClinic.doctor_signature_url || '';

  // Resolve Patient (Real data from patient prop or populated data.patient_id or data fields)
  const resolvedPatient = (patient && (patient.full_name || patient.name || patient._id))
    ? patient
    : (data.patient_id && typeof data.patient_id === 'object' ? data.patient_id : {});

  const patientName = resolvedPatient.full_name || resolvedPatient.name || data.patient_name || 'Patient';
  const patientGender = resolvedPatient.gender || data.patient_gender || '';
  const patientAge = resolvedPatient.age || (resolvedPatient.dob ? calculateAge(resolvedPatient.dob) : '') || data.patient_age || '';
  const patientAddress = resolvedPatient.address || data.patient_address || '';
  const patientPhone = resolvedPatient.phone || data.patient_phone || '';

  const patientMeta = [
    patientGender,
    patientAge ? `${patientAge} Yrs` : null,
  ].filter(Boolean).join(' / ');

  // Resolve Clinic Info (Real data from clinic or clinicCtx)
  const clinicName = resolvedClinic.name || resolvedClinic.clinicName || '';
  const tagline = resolvedClinic.tagline || '';
  const clinicAddress = resolvedClinic.address || '';
  const clinicPhone = resolvedClinic.phone || '';
  const clinicEmail = resolvedClinic.email || '';
  const clinicWebsite = resolvedClinic.website || '';
  const visitingHours = resolvedClinic.visit_hours || resolvedClinic.visitingHours || '';
  const openDays = resolvedClinic.open_days || resolvedClinic.openDays || '';

  const logoUrl = resolvedClinic.logo_url || resolvedClinic.logoUrl || resolveAsset(resolvedClinic.logo) || resolveAsset(resolvedClinic.profile_url) || '';
  const stampUrl = resolveAsset(resolvedClinic.stamp) || resolvedClinic.stamp_url || resolvedClinic.stampUrl || '';

  const issueDate = data.createdAt
    ? new Date(data.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
    : new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  // Follow-up Date formatting for Next Visit
  const followUpDateStr = data.follow_up_date
    ? new Date(data.follow_up_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
    : (data.clinical?.follow_up_date ? new Date(data.clinical.follow_up_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '');

  const handleDownloadServerPdf = async () => {
    if (!data._id) return;
    try {
      setDownloadingServerPdf(true);
      let blob;
      let filePrefix = 'Prescription';
      if (type === 'certificate') {
        blob = await certificateAPI.getPdfBlob(data._id);
        filePrefix = 'Certificate';
      } else if (type === 'consent') {
        blob = await consentAPI.getPdfBlob(data._id);
        filePrefix = 'Consent';
      } else {
        blob = await prescriptionAPI.getPdfBlob(data._id);
      }
      const url = window.URL.createObjectURL(new Blob([blob], { type: 'application/pdf' }));
      const a = document.createElement('a');
      a.href = url;
      a.download = `${filePrefix}_${(patientName || 'Patient').replace(/\s+/g, '_')}_${data._id}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error('Failed to download server PDF:', err);
      handlePrint();
    } finally {
      setDownloadingServerPdf(false);
    }
  };

  const handlePrint = () => {
    const printContent = printRef.current.innerHTML;
    const printWindow = window.open('', '_blank', 'width=900,height=1000');

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${type.toUpperCase()} - ${patientName}</title>
          <style>
            @page {
              size: A4;
              margin: 14mm 18mm 14mm 18mm;
            }
            * {
              box-sizing: border-box;
              margin: 0;
              padding: 0;
            }
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
              color: #0F172A;
              margin: 0;
              padding: 0;
              background: #fff;
              -webkit-print-color-adjust: exact !important;
              print-color-adjust: exact !important;
              font-size: 11px;
              line-height: 1.45;
            }
            .pdf-container {
              width: 100%;
              max-width: 800px;
              margin: 0 auto;
              box-sizing: border-box;
            }
            .letterhead-placeholder {
              display: block !important;
              height: ${headerMarginMm}mm !important;
              min-height: ${headerMarginMm}mm !important;
              border: none !important;
              background: transparent !important;
              color: transparent !important;
            }
            @media print {
              .no-print { display: none !important; }
              .letterhead-placeholder {
                border: none !important;
                background: transparent !important;
                color: transparent !important;
              }
            }
          </style>
        </head>
        <body>
          <div class="pdf-container">
            ${printContent}
          </div>
          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="right-drawer-backdrop" onClick={onClose} style={{ zIndex: 1000 }}>
      <div
        className="card"
        onClick={(e) => e.stopPropagation()}
        style={{
          maxWidth: '850px',
          width: '92%',
          maxHeight: '94vh',
          display: 'flex',
          flexDirection: 'column',
          borderRadius: '16px',
          overflow: 'hidden',
          padding: 0
        }}
      >
        {/* Header Action Bar */}
        <div style={{ padding: '14px 20px', background: 'var(--color-bg-secondary)', borderBottom: '1px solid var(--color-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Sparkles size={18} color={primaryColor} />
            <h3 style={{ fontSize: '15px', fontWeight: 'bold', margin: 0 }}>
              PDF Print Preview ({type.charAt(0).toUpperCase() + type.slice(1)})
            </h3>
            {headerMode === 'letterhead' && (
              <span className="badge badge-warning" style={{ fontSize: '11px', padding: '2px 8px' }}>
                Letterhead Pad ({headerMarginMm}mm)
              </span>
            )}
          </div>
          <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
            {data._id && (
              <button
                className="btn btn-secondary"
                onClick={handleDownloadServerPdf}
                disabled={downloadingServerPdf}
                style={{ padding: '6px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <Download size={15} /> {downloadingServerPdf ? 'Generating...' : 'Server PDF'}
              </button>
            )}
            <button className="btn btn-primary" onClick={handlePrint} style={{ backgroundColor: primaryColor, borderColor: primaryColor, padding: '6px 14px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Printer size={15} /> Print / Save PDF
            </button>
            <button className="icon-btn" onClick={onClose}>
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Scrollable Document Container */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '24px', background: '#525659', display: 'flex', justifyContent: 'center' }}>
          {/* Paper A4 Container (Identical to PdfTemplateStudio & Puppeteer PDF) */}
          <div
            ref={printRef}
            style={{
              width: '100%',
              maxWidth: '720px',
              minHeight: '920px',
              background: '#FFFFFF',
              padding: '28px 32px',
              boxShadow: '0 8px 30px rgba(0,0,0,0.3)',
              borderRadius: '2px',
              fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
              color: '#0F172A',
              boxSizing: 'border-box',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
              fontSize: '11px',
              lineHeight: 1.45
            }}
          >
            <div>
              {/* TOP HEADER SECTION (Digital vs Letterhead Mode) */}
              {headerMode === 'letterhead' ? (
                <div
                  className="letterhead-placeholder"
                  style={{
                    height: `${headerMarginMm * 3.78}px`,
                    minHeight: `${headerMarginMm * 3.78}px`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: '#94A3B8',
                    fontSize: '11px',
                    marginBottom: '16px',
                    background: '#F8FAFC',
                    border: '1px dashed #CBD5E1',
                    borderRadius: '4px'
                  }}
                >
                  Pre-Printed Letterhead Reserved Space ({headerMarginMm} mm)
                </div>
              ) : (
                <div style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'flex-start',
                  borderBottom: `2px solid ${primaryColor}`,
                  paddingBottom: '12px',
                  marginBottom: '14px'
                }}>
                  {/* Doctor Info (Left) */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    {logoUrl ? (
                      <img src={logoUrl} alt="Logo" style={{ width: '64px', height: '64px', borderRadius: '8px', objectFit: 'cover' }} />
                    ) : (
                      <div style={{ width: '64px', height: '64px', background: primaryColor, color: '#fff', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '14px' }}>
                        Dr
                      </div>
                    )}
                    <div>
                      <h3 style={{ fontSize: '16px', fontWeight: 'bold', margin: '0 0 2px', color: '#0F172A' }}>
                        {doctorName ? `Dr. ${doctorName}` : 'Doctor'}
                      </h3>
                      {doctorQualification && (
                        <div style={{ fontSize: '11px', color: '#475569', marginBottom: '2px' }}>{doctorQualification}</div>
                      )}
                      {doctorReg && (
                        <div style={{ fontSize: '10px', color: primaryColor }}>
                          Reg. No: <u>{doctorReg}</u>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Clinic Info (Right) */}
                  <div style={{ textAlign: 'right', fontSize: '10px', color: '#475569', lineHeight: '1.4' }}>
                    <div style={{ fontSize: '13px', fontWeight: 'bold', color: '#0F172A', marginBottom: '2px' }}>{clinicName || 'Adixon Clinic'}</div>
                    {tagline && <div style={{ fontStyle: 'italic', marginBottom: '2px' }}>{tagline}</div>}
                    {clinicAddress && <div>{clinicAddress}</div>}
                    {visitingHours && <div>Visiting Hours: {visitingHours}</div>}
                    {openDays && <div>Open: {openDays}</div>}
                    {clinicPhone && <div>Contact: {clinicPhone}</div>}
                    {clinicEmail && <div>Mail: {clinicEmail}</div>}
                    {clinicWebsite && <div>{clinicWebsite}</div>}
                  </div>
                </div>
              )}

              {/* DOCUMENT TITLE HEADER */}
              <div style={{ textAlign: 'center', marginBottom: '16px' }}>
                <h2 style={{ fontSize: '15px', fontWeight: 'bold', color: primaryColor, textTransform: 'uppercase', letterSpacing: '1.5px', margin: 0 }}>
                  {type === 'prescription' ? 'PRESCRIPTION'
                    : type === 'certificate' ? (data.certificate_type || 'MEDICAL CERTIFICATE')
                      : type === 'instruction' ? (data.title || 'PATIENT INSTRUCTION')
                        : (data.title || 'INFORMED CONSENT')}
                </h2>
                <div style={{ width: '50px', height: '2px', background: primaryColor, margin: '4px auto 0' }} />
              </div>

              {/* PATIENT BANNER */}
              <div style={{
                textAlign: 'center',
                fontSize: '11.5px',
                color: '#475569',
                marginBottom: '16px',
                background: '#F8FAFC',
                padding: '8px 12px',
                borderRadius: '6px',
                border: '1px solid #E2E8F0'
              }}>
                <div>
                  Patient : <strong style={{ color: '#0F172A', fontSize: '12px' }}>{patientName}{patientMeta ? `, ${patientMeta}` : ''}</strong>
                  <span style={{ margin: '0 8px' }}>•</span>
                  <span>Date : <strong>{issueDate}</strong></span>
                </div>
                {(showPatientAddress && patientAddress || showPatientPhone && patientPhone) && (
                  <div style={{ fontSize: '10.5px', color: '#64748B', marginTop: '2px' }}>
                    {showPatientAddress && patientAddress && <span>Address: {patientAddress} </span>}
                    {showPatientPhone && patientPhone && <span>• Phone: {patientPhone}</span>}
                  </div>
                )}
              </div>

              {/* 1. PRESCRIPTION SPECIFIC BODY (2 COLUMN LAYOUT) */}
              {type === 'prescription' && (
                <div>
                  <div style={{ display: 'grid', gridTemplateColumns: '1.05fr 1.35fr', gap: '20px' }}>
                    {/* Left Column: Vitals & History */}
                    <div>
                      {/* Vitals */}
                      {showVitals && data.vitals && (
                        <div style={{ marginBottom: '12px' }}>
                          <div style={{ fontWeight: 'bold', color: primaryColor, marginBottom: '4px', borderLeft: `3px solid ${primaryColor}`, paddingLeft: '6px' }}>
                            Vitals
                          </div>
                          {data.vitals.blood_pressure && <div style={{ marginBottom: '2px' }}>BP : <strong>{data.vitals.blood_pressure}</strong> mmHg</div>}
                          {data.vitals.pulse_rate && <div style={{ marginBottom: '2px' }}>Pulse : <strong>{data.vitals.pulse_rate}</strong> bpm</div>}
                          {data.vitals.temperature && <div style={{ marginBottom: '2px' }}>Temp : <strong>{data.vitals.temperature}</strong> °F</div>}
                          {data.vitals.spo2 && <div style={{ marginBottom: '2px' }}>SpO2 : <strong>{data.vitals.spo2}</strong> %</div>}
                          {data.vitals.weight && <div style={{ marginBottom: '2px' }}>Weight : <strong>{data.vitals.weight}</strong> kg</div>}
                          {data.vitals.height && <div style={{ marginBottom: '2px' }}>Height : <strong>{data.vitals.height}</strong> cm</div>}
                          {data.vitals.blood_sugar && <div style={{ marginBottom: '2px' }}>Blood Sugar : <strong>{data.vitals.blood_sugar}</strong> mg/dL</div>}
                          {data.vitals.hemoglobin && <div style={{ marginBottom: '2px' }}>Hemoglobin : <strong>{data.vitals.hemoglobin}</strong> g/dL</div>}
                          {data.vitals.respiration_rate && <div style={{ marginBottom: '2px' }}>Respiration : <strong>{data.vitals.respiration_rate}</strong> /min</div>}
                        </div>
                      )}

                      {/* Clinical details */}
                      {data.clinical && (
                        <div style={{ marginTop: '8px' }}>
                          {data.clinical.allergy && (
                            <div style={{ marginBottom: '4px' }}>
                              <strong style={{ color: primaryColor }}>Allergies:</strong> {data.clinical.allergy}
                            </div>
                          )}
                          {data.clinical.chief_complaint && (
                            <div style={{ marginBottom: '4px' }}>
                              <strong style={{ color: primaryColor }}>Chief Complaint:</strong> {data.clinical.chief_complaint}
                            </div>
                          )}
                          {data.clinical.patient_history && (
                            <div style={{ marginBottom: '4px' }}>
                              <strong style={{ color: primaryColor }}>Patient History:</strong> {data.clinical.patient_history}
                            </div>
                          )}
                          {data.clinical.findings && (
                            <div style={{ marginBottom: '4px' }}>
                              <strong style={{ color: primaryColor }}>Findings:</strong> {data.clinical.findings}
                            </div>
                          )}
                          {data.clinical.treatment && (
                            <div style={{ marginBottom: '4px' }}>
                              <strong style={{ color: primaryColor }}>Treatment/Advice:</strong> {data.clinical.treatment}
                            </div>
                          )}
                          {data.clinical.notes && (
                            <div style={{ marginBottom: '4px' }}>
                              <strong style={{ color: primaryColor }}>Notes:</strong> {data.clinical.notes}
                            </div>
                          )}
                        </div>
                      )}

                      {/* Diagnosis */}
                      {showDiagnosis && data.clinical?.diagnosis && (
                        <div style={{ marginTop: '10px', fontSize: '12px', fontWeight: 'bold', color: '#0F172A' }}>
                          Diagnosis : {data.clinical.diagnosis}
                        </div>
                      )}

                      {/* Advice / Labs */}
                      {showAdvice && data.labs && data.labs.length > 0 && (
                        <div style={{ marginTop: '12px' }}>
                          <div style={{ fontWeight: 'bold', color: primaryColor, marginBottom: '4px' }}>Advice / Labs:</div>
                          <ul style={{ margin: 0, paddingLeft: '16px' }}>
                            {data.labs.map((l, lIdx) => (
                              <li key={lIdx} style={{ marginBottom: '2px' }}>{typeof l === 'string' ? l : (l.name || l.lab_test)}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>

                    {/* Right Column: Rx Medicines & Next Visit */}
                    <div>
                      <div style={{ fontSize: '16px', fontWeight: '800', color: primaryColor, marginBottom: '10px', letterSpacing: '0.5px' }}>
                        Rx (Medicines)
                      </div>

                      {data.medicines && data.medicines.length > 0 ? (
                        data.medicines.map((m, idx) => (
                          <div key={idx} style={{ marginBottom: '10px', borderBottom: '1px dashed #E2E8F0', paddingBottom: '6px' }}>
                            <div style={{ fontSize: '11.5px', fontWeight: 'bold', color: '#0F172A', marginBottom: '2px' }}>
                              {idx + 1}. {m.name} {m.quantity ? `(Qty: ${m.quantity})` : ''}
                            </div>
                            <div style={{ fontSize: '10.5px', color: '#334155' }}>
                              {[m.frequency, m.instruction, m.no_of_days ? `for ${m.no_of_days} Days` : null, m.route ? `(${m.route})` : null].filter(Boolean).join(' • ')}
                            </div>
                            {m.additional_comments && (
                              <div style={{ fontStyle: 'italic', fontSize: '10px', color: '#64748B', marginTop: '2px' }}>
                                Note: {m.additional_comments}
                              </div>
                            )}
                          </div>
                        ))
                      ) : (
                        <div style={{ color: '#94A3B8', fontStyle: 'italic' }}>No medicines prescribed</div>
                      )}

                      {/* Next Visit */}
                      {showNextVisit && followUpDateStr && (
                        <div style={{ marginTop: '20px', fontWeight: 'bold', fontSize: '11px', color: '#0F172A' }}>
                          Next Follow-up Visit: {followUpDateStr}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {/* 2. CERTIFICATE SPECIFIC */}
              {type === 'certificate' && (
                <div style={{ fontSize: '12px', lineHeight: '1.8', color: '#0F172A', marginTop: '12px' }}>
                  {data.duration && (
                    <div style={{ marginBottom: '14px', background: '#F1F5F9', padding: '6px 12px', borderRadius: '6px', fontWeight: 'bold', display: 'inline-block' }}>
                      Duration / Leave: {data.duration}
                    </div>
                  )}

                  <div style={{ whiteSpace: 'pre-wrap', marginBottom: '16px' }}>
                    {data.content || 'This is to certify that the patient has been examined and advised recovery rest.'}
                  </div>

                  {data.remark && (
                    <div style={{ marginTop: '14px', borderLeft: `3px solid ${primaryColor}`, paddingLeft: '10px', fontStyle: 'italic', color: '#475569' }}>
                      <strong>Clinical Remarks:</strong> {data.remark}
                    </div>
                  )}
                </div>
              )}

              {/* 3. INSTRUCTION SPECIFIC */}
              {type === 'instruction' && (
                <div style={{ fontSize: '12px', lineHeight: '1.8', color: '#0F172A', marginTop: '12px' }}>
                  <div style={{ whiteSpace: 'pre-wrap' }}>
                    {data.description || data.content || 'Please follow all medical guidelines as instructed.'}
                  </div>
                </div>
              )}

              {/* 4. CONSENT SPECIFIC */}
              {type === 'consent' && (
                <div style={{ fontSize: '12px', lineHeight: '1.75', color: '#0F172A', marginTop: '12px' }}>
                  <div style={{ whiteSpace: 'pre-wrap', marginBottom: '24px' }}>
                    {data.content || 'I hereby give full consent to the medical procedure and treatment as explained by the practitioner.'}
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: '30px' }}>
                    {/* Patient Signature */}
                    <div style={{ border: '1px solid #CBD5E1', padding: '10px 14px', borderRadius: '6px', minWidth: '170px', textAlign: 'center' }}>
                      {data.patient_signature && (data.patient_signature.startsWith('http') || data.patient_signature.startsWith('data:')) ? (
                        <img src={data.patient_signature} alt="Patient Sig" style={{ height: '36px', objectFit: 'contain' }} />
                      ) : data.patient_signature ? (
                        <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Brush Script MT', cursive, serif", fontSize: '18px', fontStyle: 'italic', color: '#0F172A' }}>
                          {data.patient_signature}
                        </div>
                      ) : (
                        <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#94A3B8', fontSize: '10px' }}>Signature</div>
                      )}
                      <div style={{ borderTop: '1px solid #94A3B8', marginTop: '6px', paddingTop: '4px', fontSize: '10px', fontWeight: 'bold' }}>
                        Patient / Guardian Signature
                      </div>
                      <div style={{ fontSize: '9px', color: '#64748B' }}>{patientName}</div>
                    </div>

                    {/* Stamp */}
                    {showStamp && (
                      <div style={{ textAlign: 'center' }}>
                        {stampUrl ? (
                          <img src={stampUrl} alt="Stamp" style={{ width: '65px', height: '65px', objectFit: 'contain' }} />
                        ) : (
                          <div style={{ width: '60px', height: '60px', borderRadius: '50%', border: `1.5px dashed ${primaryColor}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '9px', color: primaryColor }}>
                            STAMP
                          </div>
                        )}
                      </div>
                    )}

                    {/* Doctor Signature */}
                    <div style={{ border: '1px solid #CBD5E1', padding: '10px 14px', borderRadius: '6px', minWidth: '170px', textAlign: 'center' }}>
                      {showSignature && signatureUrl ? (
                        <img src={signatureUrl} alt="Doctor Sig" style={{ height: '36px', objectFit: 'contain' }} />
                      ) : showSignature && data.doctor_signature ? (
                        <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Brush Script MT', cursive, serif", fontSize: '18px', fontStyle: 'italic', color: '#0F172A' }}>
                          {data.doctor_signature}
                        </div>
                      ) : (
                        <div style={{ height: '36px' }} />
                      )}
                      <div style={{ borderTop: '1px solid #94A3B8', marginTop: '6px', paddingTop: '4px', fontSize: '10px', fontWeight: 'bold' }}>
                        Doctor Witness Signature
                      </div>
                      <div style={{ fontSize: '9px', color: '#64748B' }}>{doctorName ? `Dr. ${doctorName}` : 'Attending Doctor'}</div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* BOTTOM SECTION: Stamp, Signature & Footer Strip (For Prescription & Certificate) */}
            {type !== 'consent' && (
              <div style={{ marginTop: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '12px' }}>
                  {/* Stamp */}
                  <div style={{ width: '70px', height: '70px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    {showStamp && (
                      stampUrl ? (
                        <img src={stampUrl} alt="Stamp" style={{ maxWidth: '70px', maxHeight: '70px', objectFit: 'contain' }} />
                      ) : (
                        <div style={{
                          width: '60px',
                          height: '60px',
                          borderRadius: '50%',
                          border: `2px dashed ${primaryColor}60`,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          color: `${primaryColor}90`,
                          fontSize: '9px',
                          textAlign: 'center'
                        }}>
                          CLINIC STAMP
                        </div>
                      )
                    )}
                  </div>

                  {/* Signature */}
                  {showSignature && (
                    <div style={{ textAlign: 'center', minWidth: '130px' }}>
                      {signatureUrl ? (
                        <img src={signatureUrl} alt="Doctor Signature" style={{ maxHeight: '38px', objectFit: 'contain', marginBottom: '2px' }} />
                      ) : (
                        <div style={{ height: '32px', color: '#94A3B8', fontSize: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                          Digital Signature
                        </div>
                      )}
                      <div style={{ width: '120px', height: '1px', background: '#64748B', margin: '0 auto 4px auto' }} />
                      <div style={{ fontSize: '11px', fontWeight: 'bold', color: '#0F172A' }}>
                        {doctorName ? `Dr. ${doctorName}` : 'Attending Doctor'}
                      </div>
                      {doctorQualification && <div style={{ fontSize: '9.5px', color: '#64748B' }}>{doctorQualification}</div>}
                      {doctorReg && <div style={{ fontSize: '9px', color: '#64748B' }}>Reg: {doctorReg}</div>}
                    </div>
                  )}
                </div>

                {/* Footer Strip */}
                {showFooter && (
                  <div style={{
                    background: '#F1F5F9',
                    padding: '6px 10px',
                    borderRadius: '4px',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    fontSize: '9.5px',
                    color: '#475569'
                  }}>
                    <div>{clinicName} {clinicPhone && `• Contact: ${clinicPhone}`}</div>
                    <div>{footerText}</div>
                  </div>
                )}
              </div>
            )}

            {/* CONSENT FOOTER BAR */}
            {type === 'consent' && showFooter && (
              <div style={{
                marginTop: '20px',
                background: '#F1F5F9',
                padding: '6px 10px',
                borderRadius: '4px',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                fontSize: '9.5px',
                color: '#475569'
              }}>
                <div>{clinicName} {clinicPhone && `• Contact: ${clinicPhone}`}</div>
                <div>{footerText}</div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
