import React, { useState, useEffect } from 'react';
import { clinicAPI, prescriptionAPI, certificateAPI, consentAPI } from '../services/api';
import { 
  FileText, 
  Palette, 
  Layout, 
  Save, 
  RotateCcw, 
  CheckCircle2, 
  Sparkles, 
  Sliders, 
  Eye, 
  FileCheck,
  Building2,
  Printer,
  Calendar
} from 'lucide-react';

const PRESET_COLORS = [
  { name: 'Adixon Teal', hex: '#0F766E' },
  { name: 'Classic Navy', hex: '#1E3A8A' },
  { name: 'Sky Medical', hex: '#0284C7' },
  { name: 'Emerald', hex: '#059669' },
  { name: 'Deep Charcoal', hex: '#334155' },
  { name: 'Indigo', hex: '#4F46E5' },
];

export default function PdfTemplateStudio({ clinic, onSaveSuccess }) {
  const clinicId = clinic?._id || clinic?.id;

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState({ type: '', text: '' });

  // Document Type Tab for Preview: 'prescription' | 'certificate' | 'consent'
  const [docTab, setDocTab] = useState('prescription');

  // Real sample documents for this clinic
  const [realPrescription, setRealPrescription] = useState(null);
  const [realCertificate, setRealCertificate] = useState(null);
  const [realConsent, setRealConsent] = useState(null);

  // Template Form State
  const [headerMode, setHeaderMode] = useState('digital'); // 'digital' | 'letterhead'
  const [headerMarginMm, setHeaderMarginMm] = useState(50);
  const [primaryColor, setPrimaryColor] = useState('#0F766E');
  const [fontSize, setFontSize] = useState('standard');

  const [showDate, setShowDate] = useState(true);
  const [useCustomDate, setUseCustomDate] = useState(false);
  const [customDate, setCustomDate] = useState('');

  const [showVitals, setShowVitals] = useState(true);
  const [showDiagnosis, setShowDiagnosis] = useState(true);
  const [showAdvice, setShowAdvice] = useState(true);
  const [showPatientAddress, setShowPatientAddress] = useState(true);
  const [showPatientPhone, setShowPatientPhone] = useState(true);
  const [showNextVisit, setShowNextVisit] = useState(true);
  const [showSignature, setShowSignature] = useState(true);
  const [showStamp, setShowStamp] = useState(true);
  const [showFooter, setShowFooter] = useState(true);
  const [footerText, setFooterText] = useState('Generated by Adixon Clinic OS');

  // Load existing template and real records from backend
  useEffect(() => {
    if (!clinicId) return;
    let isMounted = true;
    setLoading(true);

    // 1. Fetch clinic template
    clinicAPI.getPdfTemplate(clinicId)
      .then((res) => {
        if (!isMounted) return;
        if (res?.success && res?.data) {
          const t = res.data;
          setHeaderMode(t.header_mode || 'digital');
          setHeaderMarginMm(t.header_margin_mm ?? 50);
          setPrimaryColor(t.primary_color || '#0F766E');
          setFontSize(t.font_size || 'standard');
          setShowDate(t.show_date !== false);
          setCustomDate(t.custom_date || '');
          setUseCustomDate(Boolean(t.custom_date && t.custom_date.trim().length > 0));
          setShowVitals(t.show_vitals !== false);
          setShowDiagnosis(t.show_diagnosis !== false);
          setShowAdvice(t.show_advice !== false);
          setShowPatientAddress(t.show_patient_address !== false);
          setShowPatientPhone(t.show_patient_phone !== false);
          setShowNextVisit(t.show_next_visit !== false);
          setShowSignature(t.show_signature !== false);
          setShowStamp(t.show_stamp !== false);
          setShowFooter(t.show_footer !== false);
          setFooterText(t.footer_text || 'Generated by Adixon Clinic OS');
        }
      })
      .catch((err) => {
        console.error('Failed to load PDF template:', err);
      })
      .finally(() => {
        if (isMounted) setLoading(false);
      });

    // 2. Fetch real samples for preview
    prescriptionAPI.getPrescriptions({ clinic_id: clinicId, limit: 1 })
      .then((res) => {
        if (!isMounted) return;
        const item = res?.data?.[0] || res?.data?.data?.[0];
        if (item) setRealPrescription(item);
      })
      .catch(() => {});

    certificateAPI.getCertificates({ clinic_id: clinicId, limit: 1 })
      .then((res) => {
        if (!isMounted) return;
        const item = res?.data?.[0] || res?.data?.data?.[0];
        if (item) setRealCertificate(item);
      })
      .catch(() => {});

    consentAPI.getConsents({ clinic_id: clinicId, limit: 1 })
      .then((res) => {
        if (!isMounted) return;
        const item = res?.data?.[0] || res?.data?.data?.[0];
        if (item) setRealConsent(item);
      })
      .catch(() => {});

    return () => { isMounted = false; };
  }, [clinicId]);

  const handleSave = async () => {
    if (!clinicId) return;
    setSaving(true);
    setMsg({ type: '', text: '' });

    const payload = {
      header_mode: headerMode,
      header_margin_mm: Number(headerMarginMm),
      primary_color: primaryColor,
      font_size: fontSize,
      show_date: showDate,
      custom_date: (showDate && useCustomDate) ? customDate.trim() : '',
      show_vitals: showVitals,
      show_diagnosis: showDiagnosis,
      show_advice: showAdvice,
      show_patient_address: showPatientAddress,
      show_patient_phone: showPatientPhone,
      show_next_visit: showNextVisit,
      show_signature: showSignature,
      show_stamp: showStamp,
      show_footer: showFooter,
      footer_text: footerText,
    };

    try {
      const res = await clinicAPI.updatePdfTemplate(clinicId, payload);
      if (res?.success) {
        setMsg({ type: 'success', text: 'PDF template settings saved successfully!' });
        if (onSaveSuccess) onSaveSuccess(res.data);
      } else {
        setMsg({ type: 'error', text: res?.message || 'Failed to save template.' });
      }
    } catch (err) {
      setMsg({ type: 'error', text: err?.response?.data?.message || err.message || 'Error saving template.' });
    } finally {
      setSaving(false);
    }
  };

  const handleResetDefaults = () => {
    setHeaderMode('digital');
    setHeaderMarginMm(50);
    setPrimaryColor('#0F766E');
    setFontSize('standard');
    setShowVitals(true);
    setShowDiagnosis(true);
    setShowAdvice(true);
    setShowPatientAddress(true);
    setShowPatientPhone(true);
    setShowNextVisit(true);
    setShowSignature(true);
    setShowStamp(true);
    setShowFooter(true);
    setFooterText('Generated by Adixon Clinic OS');
  };

  // Real clinic details for preview
  const clinicName = clinic?.name || clinic?.clinicName || '';
  const clinicPhone = clinic?.phone || '';
  const clinicEmail = clinic?.email || '';
  const clinicAddress = clinic?.address || '';
  const clinicWebsite = clinic?.website || '';
  const doctorName = clinic?.doctor_name || clinic?.doctorName || '';
  const doctorQual = clinic?.doctor_qualification || clinic?.doctorQualification || '';
  const doctorReg = clinic?.registration_number || clinic?.registrationNumber || '';
  
  const resolveAsset = (asset) => {
    if (!asset) return '';
    if (typeof asset === 'string') return asset.trim();
    if (typeof asset === 'object') return asset.secure_url || asset.url || '';
    return '';
  };
  const logoUrl = resolveAsset(clinic?.logo) || resolveAsset(clinic?.profile_url) || '/adixon-logo.png';
  const signatureUrl = resolveAsset(clinic?.doctor_signature);
  const stampUrl = resolveAsset(clinic?.stamp);

  // Resolved sample data for active tab
  const samplePatientName = docTab === 'prescription' 
    ? (realPrescription?.patient_id?.full_name || 'Rahul Sharma')
    : docTab === 'certificate'
    ? (realCertificate?.patient_id?.full_name || 'Ananya Gupta')
    : (realConsent?.patient_id?.full_name || 'Vikas Verma');

  const samplePatientMeta = docTab === 'prescription'
    ? (realPrescription?.patient_id ? `${realPrescription.patient_id.gender || 'Male'} / ${realPrescription.patient_id.age || '32'} Yrs` : 'Male / 32 Yrs')
    : docTab === 'certificate'
    ? (realCertificate?.patient_id ? `${realCertificate.patient_id.gender || 'Female'} / ${realCertificate.patient_id.age || '28'} Yrs` : 'Female / 28 Yrs')
    : (realConsent?.patient_id ? `${realConsent.patient_id.gender || 'Male'} / ${realConsent.patient_id.age || '45'} Yrs` : 'Male / 45 Yrs');

  const samplePatientAddress = docTab === 'prescription'
    ? (realPrescription?.patient_id?.address || 'Sector 4, Central Colony')
    : docTab === 'certificate'
    ? (realCertificate?.patient_id?.address || '12 Park Avenue')
    : (realConsent?.patient_id?.address || 'Greenfield Heights');

  const samplePatientPhone = docTab === 'prescription'
    ? (realPrescription?.patient_id?.phone || '9876543210')
    : docTab === 'certificate'
    ? (realCertificate?.patient_id?.phone || '9812345678')
    : (realConsent?.patient_id?.phone || '9988776655');

  const todayStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const effectiveDate = (showDate && useCustomDate && customDate.trim()) ? customDate.trim() : todayStr;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Studio Header Bar */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        background: 'var(--color-bg-secondary)',
        padding: '16px 20px',
        borderRadius: '12px',
        border: '1px solid var(--color-border)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div style={{
            width: '40px',
            height: '40px',
            borderRadius: '10px',
            background: `${primaryColor}20`,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: primaryColor
          }}>
            <Sliders size={22} />
          </div>
          <div>
            <h3 style={{ fontSize: '16px', fontWeight: 'bold', margin: 0, color: 'var(--color-text)' }}>
              Clinic PDF Template Studio
            </h3>
            <p style={{ fontSize: '12px', color: 'var(--color-text-secondary)', margin: '2px 0 0' }}>
              Unified template settings for Prescriptions, Certificates, and Consents.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
          <button 
            className="btn btn-secondary" 
            onClick={handleResetDefaults}
            disabled={saving || loading}
            style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px' }}
          >
            <RotateCcw size={14} /> Reset Defaults
          </button>
          <button 
            className="btn btn-primary" 
            onClick={handleSave}
            disabled={saving || loading}
            style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: '6px', 
              fontSize: '13px',
              backgroundColor: primaryColor,
              borderColor: primaryColor
            }}
          >
            <Save size={14} /> {saving ? 'Saving...' : 'Save Template'}
          </button>
        </div>
      </div>

      {msg.text && (
        <div style={{
          padding: '12px 16px',
          borderRadius: '8px',
          fontSize: '13px',
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          background: msg.type === 'success' ? '#ECFDF5' : '#FEF2F2',
          color: msg.type === 'success' ? '#065F46' : '#991B1B',
          border: `1px solid ${msg.type === 'success' ? '#A7F3D0' : '#FECACA'}`
        }}>
          <CheckCircle2 size={16} />
          {msg.text}
        </div>
      )}

      {/* Main Studio Grid: Controls on Left, Live A4 Preview on Right */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'minmax(360px, 420px) 1fr',
        gap: '24px',
        alignItems: 'flex-start'
      }}>
        {/* LEFT COLUMN: Controls */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Card 1: Header Mode */}
          <div className="card" style={{ padding: '18px', borderRadius: '12px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
              <Layout size={18} color={primaryColor} />
              <h4 style={{ fontSize: '14px', fontWeight: 'bold', margin: 0, color: 'var(--color-text)' }}>
                Header Layout Mode
              </h4>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginBottom: '16px' }}>
              <div 
                onClick={() => setHeaderMode('digital')}
                style={{
                  padding: '12px',
                  borderRadius: '8px',
                  border: `2px solid ${headerMode === 'digital' ? primaryColor : 'var(--color-border)'}`,
                  background: headerMode === 'digital' ? `${primaryColor}10` : 'transparent',
                  cursor: 'pointer',
                  textAlign: 'center'
                }}
              >
                <div style={{ fontWeight: 'bold', fontSize: '13px', color: 'var(--color-text)' }}>Digital Header</div>
                <div style={{ fontSize: '11px', color: 'var(--color-text-secondary)', marginTop: '4px' }}>
                  Prints clinic branding & doctor header
                </div>
              </div>

              <div 
                onClick={() => setHeaderMode('letterhead')}
                style={{
                  padding: '12px',
                  borderRadius: '8px',
                  border: `2px solid ${headerMode === 'letterhead' ? primaryColor : 'var(--color-border)'}`,
                  background: headerMode === 'letterhead' ? `${primaryColor}10` : 'transparent',
                  cursor: 'pointer',
                  textAlign: 'center'
                }}
              >
                <div style={{ fontWeight: 'bold', fontSize: '13px', color: 'var(--color-text)' }}>Letterhead Pad</div>
                <div style={{ fontSize: '11px', color: 'var(--color-text-secondary)', marginTop: '4px' }}>
                  Leaves blank space for pre-printed paper
                </div>
              </div>
            </div>

            {headerMode === 'letterhead' && (
              <div style={{ background: 'var(--color-bg-secondary)', padding: '12px', borderRadius: '8px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                  <label style={{ fontSize: '12px', fontWeight: 'bold', color: 'var(--color-text)' }}>
                    Top Margin Space (mm):
                  </label>
                  <span style={{ fontSize: '12px', fontWeight: 'bold', color: primaryColor }}>
                    {headerMarginMm} mm
                  </span>
                </div>
                <input 
                  type="range"
                  min="20"
                  max="120"
                  step="5"
                  value={headerMarginMm}
                  onChange={(e) => setHeaderMarginMm(e.target.value)}
                  style={{ width: '100%', accentColor: primaryColor }}
                />
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10px', color: 'var(--color-text-secondary)', marginTop: '4px' }}>
                  <span>20 mm (Compact)</span>
                  <span>50 mm (Default)</span>
                  <span>120 mm (Large)</span>
                </div>
              </div>
            )}
          </div>

          {/* Card 2: Primary Accent Color */}
          <div className="card" style={{ padding: '18px', borderRadius: '12px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
              <Palette size={18} color={primaryColor} />
              <h4 style={{ fontSize: '14px', fontWeight: 'bold', margin: 0, color: 'var(--color-text)' }}>
                Document Theme Color
              </h4>
            </div>

            <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '14px' }}>
              {PRESET_COLORS.map((c) => (
                <button
                  key={c.hex}
                  type="button"
                  onClick={() => setPrimaryColor(c.hex)}
                  style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '8px',
                    backgroundColor: c.hex,
                    border: primaryColor === c.hex ? '3px solid #000000' : '2px solid transparent',
                    cursor: 'pointer',
                    outline: 'none',
                    boxShadow: primaryColor === c.hex ? '0 0 0 2px rgba(0,0,0,0.2)' : 'none',
                  }}
                  title={c.name}
                />
              ))}
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <input 
                type="color"
                value={primaryColor}
                onChange={(e) => setPrimaryColor(e.target.value)}
                style={{ width: '40px', height: '36px', padding: 0, border: 'none', borderRadius: '6px', cursor: 'pointer' }}
              />
              <input 
                type="text"
                className="input"
                value={primaryColor}
                onChange={(e) => setPrimaryColor(e.target.value)}
                style={{ width: '100px', fontSize: '12px' }}
              />
            </div>
          </div>

          {/* Card 3: Visibility Options */}
          <div className="card" style={{ padding: '18px', borderRadius: '12px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
              <FileCheck size={18} color={primaryColor} />
              <h4 style={{ fontSize: '14px', fontWeight: 'bold', margin: 0, color: 'var(--color-text)' }}>
                Template Options
              </h4>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {[
                { label: 'Document Date', desc: 'Show date on prescription and documents', state: showDate, setter: setShowDate },
                { label: 'Next Visit / Follow-up Date', desc: 'Show scheduled return appointment date', state: showNextVisit, setter: setShowNextVisit },
                { label: 'Doctor Signature', desc: 'Show digital signature block on output', state: showSignature, setter: setShowSignature },
                { label: 'Clinic Stamp', desc: 'Display authorized clinic seal/stamp', state: showStamp, setter: setShowStamp },
                { label: 'Clinic Footer Strip', desc: 'Show clinic info footer banner at the bottom', state: showFooter, setter: setShowFooter },
              ].map((item, idx) => (
                <div key={idx}>
                  <label 
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      padding: '8px 10px',
                      borderRadius: '6px',
                      background: 'var(--color-bg-secondary)',
                      cursor: 'pointer'
                    }}
                  >
                    <div>
                      <div style={{ fontSize: '12.5px', fontWeight: '500', color: 'var(--color-text)' }}>{item.label}</div>
                      <div style={{ fontSize: '10.5px', color: 'var(--color-text-secondary)' }}>{item.desc}</div>
                    </div>
                    <input 
                      type="checkbox"
                      checked={item.state}
                      onChange={(e) => item.setter(e.target.checked)}
                      style={{ width: '17px', height: '17px', accentColor: primaryColor, cursor: 'pointer' }}
                    />
                  </label>

                  {/* Custom Date Override Sub-option under Document Date */}
                  {item.label === 'Document Date' && showDate && (
                    <div style={{
                      marginTop: '6px',
                      padding: '12px',
                      borderRadius: '8px',
                      background: 'var(--color-bg-primary)',
                      border: '1px solid var(--color-border)',
                      marginLeft: '6px'
                    }}>
                      <label 
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'space-between',
                          cursor: 'pointer',
                          marginBottom: useCustomDate ? '10px' : 0
                        }}
                      >
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                          <Calendar size={15} color={primaryColor} />
                          <div>
                            <div style={{ fontSize: '12px', fontWeight: '600', color: 'var(--color-text)' }}>
                              Custom Date Override
                            </div>
                            <div style={{ fontSize: '10.5px', color: 'var(--color-text-secondary)' }}>
                              {useCustomDate && customDate ? `Active: ${customDate}` : 'Use a specific date instead of default date'}
                            </div>
                          </div>
                        </div>
                        <input 
                          type="checkbox"
                          checked={useCustomDate}
                          onChange={(e) => {
                            const checked = e.target.checked;
                            setUseCustomDate(checked);
                            if (checked && !customDate) {
                              setCustomDate(todayStr);
                            }
                          }}
                          style={{ width: '16px', height: '16px', accentColor: primaryColor, cursor: 'pointer' }}
                        />
                      </label>

                      {useCustomDate && (
                        <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginTop: '6px' }}>
                          <input 
                            type="text"
                            className="input"
                            placeholder="e.g. 14 Sep 2026"
                            value={customDate}
                            onChange={(e) => setCustomDate(e.target.value)}
                            style={{ flex: 1, fontSize: '12px', padding: '6px 10px', height: '34px' }}
                          />
                          <input 
                            type="date"
                            onChange={(e) => {
                              if (e.target.value) {
                                const d = new Date(e.target.value);
                                const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
                                const day = String(d.getDate()).padStart(2, '0');
                                const month = months[d.getMonth()];
                                const year = d.getFullYear();
                                setCustomDate(`${day} ${month} ${year}`);
                              }
                            }}
                            title="Pick date from calendar"
                            style={{
                              width: '38px',
                              height: '34px',
                              padding: '2px',
                              borderRadius: '6px',
                              border: '1px solid var(--color-border)',
                              cursor: 'pointer',
                              background: 'var(--color-bg-secondary)'
                            }}
                          />
                          <button
                            type="button"
                            onClick={() => setCustomDate(todayStr)}
                            className="btn btn-secondary btn-sm"
                            style={{ height: '34px', fontSize: '11px', padding: '0 10px', whiteSpace: 'nowrap' }}
                          >
                            Today
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Card 4: Footer Custom Text */}
          {showFooter && (
            <div className="card" style={{ padding: '18px', borderRadius: '12px' }}>
              <div style={{ fontSize: '13px', fontWeight: 'bold', marginBottom: '8px', color: 'var(--color-text)' }}>
                Footer Text
              </div>
              <input 
                type="text"
                className="input"
                value={footerText}
                onChange={(e) => setFooterText(e.target.value)}
                placeholder="Generated by Adixon Clinic OS"
                style={{ fontSize: '12px', width: '100%' }}
              />
            </div>
          )}
        </div>

        {/* RIGHT COLUMN: Live A4 Interactive Document Preview */}
        <div style={{
          background: '#475569',
          padding: '24px 20px',
          borderRadius: '16px',
          boxShadow: 'inset 0 2px 10px rgba(0,0,0,0.2)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          overflowX: 'auto'
        }}>
          {/* Header Bar with Live Preview Tab Switcher */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            width: '100%',
            maxWidth: '680px',
            marginBottom: '16px',
            gap: '12px',
            flexWrap: 'wrap'
          }}>
            <div style={{
              color: '#FFFFFF',
              fontSize: '12px',
              fontWeight: '600',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              letterSpacing: '0.5px'
            }}>
              <Eye size={15} /> LIVE A4 TEMPLATE PREVIEW
            </div>

            <div style={{ display: 'flex', gap: '6px', background: '#334155', padding: '4px', borderRadius: '8px' }}>
              <button
                type="button"
                onClick={() => setDocTab('prescription')}
                style={{
                  padding: '5px 12px',
                  borderRadius: '6px',
                  fontSize: '11.5px',
                  fontWeight: '600',
                  border: 'none',
                  cursor: 'pointer',
                  background: docTab === 'prescription' ? primaryColor : 'transparent',
                  color: docTab === 'prescription' ? '#FFFFFF' : '#CBD5E1',
                  transition: 'all 0.2s'
                }}
              >
                Prescription
              </button>
              <button
                type="button"
                onClick={() => setDocTab('certificate')}
                style={{
                  padding: '5px 12px',
                  borderRadius: '6px',
                  fontSize: '11.5px',
                  fontWeight: '600',
                  border: 'none',
                  cursor: 'pointer',
                  background: docTab === 'certificate' ? primaryColor : 'transparent',
                  color: docTab === 'certificate' ? '#FFFFFF' : '#CBD5E1',
                  transition: 'all 0.2s'
                }}
              >
                Certificate
              </button>
              <button
                type="button"
                onClick={() => setDocTab('consent')}
                style={{
                  padding: '5px 12px',
                  borderRadius: '6px',
                  fontSize: '11.5px',
                  fontWeight: '600',
                  border: 'none',
                  cursor: 'pointer',
                  background: docTab === 'consent' ? primaryColor : 'transparent',
                  color: docTab === 'consent' ? '#FFFFFF' : '#CBD5E1',
                  transition: 'all 0.2s'
                }}
              >
                Consent
              </button>
            </div>
          </div>

          {/* A4 Sheet Container */}
          <div style={{
            width: '100%',
            maxWidth: '680px',
            minHeight: '880px',
            background: '#FFFFFF',
            color: '#0F172A',
            padding: '28px 32px',
            boxShadow: '0 8px 30px rgba(0,0,0,0.3)',
            borderRadius: '2px',
            fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
            boxSizing: 'border-box',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            fontSize: '11px',
            lineHeight: 1.45
          }}>
            <div>
              {/* TOP HEADER SECTION */}
              {headerMode === 'letterhead' ? (
                <div style={{
                  height: `${headerMarginMm * 3}px`,
                  border: '1px dashed #CBD5E1',
                  borderRadius: '6px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: '#94A3B8',
                  fontSize: '11px',
                  marginBottom: '16px',
                  background: '#F8FAFC'
                }}>
                  Pre-Printed Letterhead Reserved Space ({headerMarginMm} mm)
                </div>
              ) : (
                <div style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'flex-start',
                  borderBottom: `2px solid ${primaryColor}`,
                  paddingBottom: '12px',
                  marginBottom: '14px'
                }}>
                  {/* Doctor Info (Left) */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    {logoUrl ? (
                      <img 
                        src={logoUrl} 
                        alt="Logo" 
                        style={{ width: '64px', height: '64px', borderRadius: '8px', objectFit: 'contain' }} 
                      />
                    ) : (
                      <div style={{
                        width: '64px',
                        height: '64px',
                        borderRadius: '8px',
                        background: primaryColor,
                        color: '#FFFFFF',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontWeight: 'bold',
                        fontSize: '14px'
                      }}>
                        Dr
                      </div>
                    )}
                    <div>
                      <h3 style={{ fontSize: '16px', fontWeight: 'bold', margin: '0 0 2px', color: '#0F172A' }}>
                        {doctorName ? `Dr. ${doctorName}` : 'Doctor'}
                      </h3>
                      {doctorQual && (
                        <div style={{ fontSize: '11px', color: '#475569', marginBottom: '2px' }}>
                          {doctorQual}
                        </div>
                      )}
                      {doctorReg && (
                        <div style={{ fontSize: '10px', color: primaryColor }}>
                          Reg. No: <u>{doctorReg}</u>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Clinic Info (Right) */}
                  <div style={{ textAlign: 'right', fontSize: '10px', color: '#475569', lineHeight: '1.4' }}>
                    <div style={{ fontSize: '13px', fontWeight: 'bold', color: '#0F172A', marginBottom: '2px' }}>
                      {clinicName || 'Adixon Clinic'}
                    </div>
                    {clinicAddress && <div>{clinicAddress}</div>}
                    {clinicPhone && <div>Contact: {clinicPhone}</div>}
                    {clinicEmail && <div>Mail: {clinicEmail}</div>}
                    {clinicWebsite && <div>{clinicWebsite}</div>}
                  </div>
                </div>
              )}

              {/* PATIENT BANNER (Clean, Centered, No box) */}
              <div style={{ 
                textAlign: 'center', 
                fontSize: '12px', 
                color: '#475569', 
                marginBottom: '16px',
                padding: '4px 0'
              }}>
                Patient : <strong style={{ color: '#0F172A', fontSize: '13px' }}>{samplePatientName}, {samplePatientMeta}</strong>
              </div>

              {/* 1. PRESCRIPTION PREVIEW */}
              {docTab === 'prescription' && (
                <div>
                  <div style={{ display: 'flex', gap: '24px', alignItems: 'flex-start' }}>
                    {/* Left Column (flex: 1.05) */}
                    <div style={{ flex: 1.05, paddingRight: '8px' }}>
                      {/* Date */}
                      {showDate && (
                        <div style={{ fontSize: '11px', marginBottom: '5px', color: '#0F172A', fontWeight: '600' }}>
                          Date : {effectiveDate}
                        </div>
                      )}

                      {showPatientAddress && (
                        <div style={{ fontSize: '11px', marginBottom: '5px', color: '#0F172A' }}>
                          Address : {samplePatientAddress}
                        </div>
                      )}

                      {showPatientPhone && (
                        <div style={{ fontSize: '11px', marginBottom: '5px', color: '#0F172A' }}>
                          Phone : {samplePatientPhone}
                        </div>
                      )}

                      {/* Vitals */}
                      {showVitals && (
                        <div style={{ marginTop: '6px' }}>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Temperature :</span> <span>25 ° F</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Height :</span> <span>125 cm</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Weight :</span> <span>10 kg</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Pulse :</span> <span>255 bpm</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>BP :</span> <span>545</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Blood Sugar :</span> <span>525 mg/dL</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Hemoglobin :</span> <span>14 g/dL</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>SpO2 :</span> <span>42 %</span></div>
                          <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Respiration Rate :</span> <span>55 /min</span></div>
                        </div>
                      )}

                      {/* Clinical details */}
                      <div style={{ marginTop: '8px' }}>
                        <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Allergies :</span> <span>{realPrescription?.clinical?.allergy || 'edfre wer frfga rtg fzxgwrtyytfry rsty rthy  byh ghh bgh na to I don\'t know what you think about it is not'}</span></div>
                        <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Chief Complaint :</span> <span>{realPrescription?.clinical?.chief_complaint || 'ghar pe hi to I don\'t know what you'}</span></div>
                        <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>History :</span> <span>{realPrescription?.clinical?.patient_history || 'thn ah ka kya hua tha ki baat nhi hai'}</span></div>
                        <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Findings :</span> <span>{realPrescription?.clinical?.findings || 'gehri meng mrng me btw I\'m not sure'}</span></div>
                        <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>Treatment/Advice :</span> <span>{realPrescription?.clinical?.treatment || 'rtuy rth  y'}</span></div>
                        <div style={{ fontSize: '11px', marginBottom: '4px', color: '#0F172A' }}><span style={{ fontWeight: '500' }}>End Note :</span> <span>{realPrescription?.clinical?.notes || 'fgh gf hj'}</span></div>
                      </div>

                      {/* Diagnosis */}
                      {showDiagnosis && (
                        <div style={{ marginTop: '10px', marginBottom: '12px', fontSize: '12px', fontWeight: '700', color: '#0F172A' }}>
                          Diagnosis : {realPrescription?.clinical?.diagnosis || 'Doctor diagnosis'}
                        </div>
                      )}

                      {/* Advice / Labs */}
                      {showAdvice && (
                        <div style={{ marginTop: '14px' }}>
                          <div style={{ fontSize: '13px', fontWeight: '700', color: primaryColor, marginBottom: '6px' }}>
                            Advice
                          </div>
                          <div style={{ fontSize: '10.5px', color: '#1E293B', marginBottom: '4px', paddingLeft: '4px' }}>
                            - CBC with GBP, Blood Urea S. Creatinine, LFT urine R/M
                          </div>
                          <div style={{ fontSize: '10.5px', color: '#1E293B', marginBottom: '4px', paddingLeft: '4px' }}>
                            - CBC, ESR, CRP. RBS Serum Uric Acid.
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Right Column (flex: 1.35) */}
                    <div style={{ flex: 1.35 }}>
                      <div style={{ fontSize: '18px', fontWeight: '800', color: primaryColor, marginBottom: '14px', letterSpacing: '0.5px' }}>
                        Rx
                      </div>

                      <div style={{ marginBottom: '14px' }}>
                        <div style={{ fontSize: '12px', fontWeight: '700', color: '#0F172A', marginBottom: '3px' }}>
                          SINAREST AF Tablet (Qty: 14)
                        </div>
                        <div style={{ fontSize: '10.5px', color: '#334155', marginBottom: '2px' }}>
                          BD (Twice A Day / 1-0-1) for 7 Days
                        </div>
                      </div>

                      <div style={{ marginBottom: '14px' }}>
                        <div style={{ fontSize: '12px', fontWeight: '700', color: '#0F172A', marginBottom: '3px' }}>
                          Pandostal-OD Capsule SR (Qty: 7)
                        </div>
                        <div style={{ fontSize: '10.5px', color: '#334155', marginBottom: '2px' }}>
                          OD (Once A Day / 1-0-0) Early Morning Empty Stomach for 1 Days
                        </div>
                      </div>

                      <div style={{ marginBottom: '14px' }}>
                        <div style={{ fontSize: '12px', fontWeight: '700', color: '#0F172A', marginBottom: '3px' }}>
                          Pexep CR 25 Tablet (Qty: 10)
                        </div>
                        <div style={{ fontSize: '10.5px', color: '#334155', marginBottom: '2px' }}>
                          HS (Before Sleep / 0-0-1) for 10 Days
                        </div>
                      </div>

                      <div style={{ marginBottom: '14px' }}>
                        <div style={{ fontSize: '12px', fontWeight: '700', color: '#0F172A', marginBottom: '3px' }}>
                          ZORYL MP 1 FORTE 1X10 (Qty: 1)
                        </div>
                        <div style={{ fontSize: '10.5px', color: '#334155', marginBottom: '2px' }}>
                          for 1 Days
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* NEXT VISIT */}
                  {showNextVisit && (
                    <div style={{ marginTop: '24px', marginBottom: '20px', fontSize: '11.5px', fontWeight: '700', color: '#0F172A' }}>
                      Next Visit: 01 Sep 2026 - tg not a good time with my family is not a good
                    </div>
                  )}
                </div>
              )}

              {/* 2. CERTIFICATE PREVIEW */}
              {docTab === 'certificate' && (
                <div style={{ fontSize: '12px', lineHeight: '1.8', color: '#0F172A', marginTop: '12px' }}>
                  {showDate && (
                    <div style={{ fontSize: '11px', marginBottom: '8px', color: '#0F172A', fontWeight: '600' }}>
                      Date : {effectiveDate}
                    </div>
                  )}
                  <div style={{ marginBottom: '14px', background: '#F1F5F9', padding: '6px 12px', borderRadius: '6px', fontWeight: 'bold', display: 'inline-block' }}>
                    Validity Duration: {realCertificate?.duration || '3 Days'}
                  </div>

                  <div style={{ whiteSpace: 'pre-wrap', marginBottom: '16px' }}>
                    {realCertificate?.content || 'This is to certify that the patient was examined at our clinic and is advised complete medical rest to recover from acute symptoms.'}
                  </div>

                  <div style={{ marginTop: '14px', borderLeft: `3px solid ${primaryColor}`, paddingLeft: '10px', fontStyle: 'italic', color: '#475569' }}>
                    <strong>Clinical Remarks:</strong> {realCertificate?.remark || 'Avoid strenuous physical actions and rest adequately.'}
                  </div>
                </div>
              )}

              {/* 3. CONSENT PREVIEW */}
              {docTab === 'consent' && (
                <div style={{ fontSize: '12px', lineHeight: '1.75', color: '#0F172A', marginTop: '12px' }}>
                  {showDate && (
                    <div style={{ fontSize: '11px', marginBottom: '8px', color: '#0F172A', fontWeight: '600' }}>
                      Date : {effectiveDate}
                    </div>
                  )}
                  <div style={{ whiteSpace: 'pre-wrap', marginBottom: '24px' }}>
                    {realConsent?.content || 'I hereby give my informed authorization and consent to undergo the proposed medical procedure and clinical treatments. The risks and benefits have been clearly explained to me.'}
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: '30px' }}>
                    {/* Patient Signature */}
                    <div style={{ border: '1px solid #CBD5E1', padding: '10px 14px', borderRadius: '6px', minWidth: '170px', textAlign: 'center' }}>
                      <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Brush Script MT', cursive, serif", fontSize: '18px', fontStyle: 'italic' }}>
                        {realConsent?.patient_signature || samplePatientName}
                      </div>
                      <div style={{ borderTop: '1px solid #94A3B8', marginTop: '6px', paddingTop: '4px', fontSize: '10px', fontWeight: 'bold' }}>
                        Patient / Guardian Signature
                      </div>
                      <div style={{ fontSize: '9px', color: '#64748B' }}>{samplePatientName}</div>
                    </div>

                    {/* Stamp */}
                    {showStamp && (
                      <div style={{ textAlign: 'center' }}>
                        {stampUrl ? (
                          <img src={stampUrl} alt="Stamp" style={{ width: '65px', height: '65px', objectFit: 'contain' }} />
                        ) : (
                          <div style={{ width: '60px', height: '60px', borderRadius: '50%', border: `1.5px dashed ${primaryColor}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '9px', color: primaryColor }}>
                            STAMP
                          </div>
                        )}
                      </div>
                    )}

                    {/* Doctor Signature */}
                    <div style={{ border: '1px solid #CBD5E1', padding: '10px 14px', borderRadius: '6px', minWidth: '170px', textAlign: 'center' }}>
                      {showSignature && signatureUrl ? (
                        <img src={signatureUrl} alt="Doctor Sig" style={{ height: '36px', objectFit: 'contain' }} />
                      ) : showSignature ? (
                        <div style={{ height: '36px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'Brush Script MT', cursive, serif", fontSize: '18px', fontStyle: 'italic' }}>
                          {realConsent?.doctor_signature || (doctorName ? `Dr. ${doctorName}` : 'Doctor')}
                        </div>
                      ) : (
                        <div style={{ height: '36px' }} />
                      )}
                      <div style={{ borderTop: '1px solid #94A3B8', marginTop: '6px', paddingTop: '4px', fontSize: '10px', fontWeight: 'bold' }}>
                        Doctor Witness Signature
                      </div>
                      <div style={{ fontSize: '9px', color: '#64748B' }}>{doctorName ? `Dr. ${doctorName}` : 'Attending Doctor'}</div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* BOTTOM SECTION: Stamp, Signature & Footer Strip (For Prescription & Certificate) */}
            {docTab !== 'consent' && (
              <div style={{ marginTop: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '12px' }}>
                  {/* Stamp */}
                  <div style={{ width: '90px', height: '90px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    {showStamp && (
                      stampUrl ? (
                        <img src={stampUrl} alt="Stamp" style={{ maxWidth: '90px', maxHeight: '90px', objectFit: 'contain' }} />
                      ) : (
                        <div style={{
                          width: '70px',
                          height: '70px',
                          borderRadius: '50%',
                          border: `2px dashed ${primaryColor}60`,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          color: `${primaryColor}90`,
                          fontSize: '9px',
                          textAlign: 'center'
                        }}>
                          CLINIC STAMP
                        </div>
                      )
                    )}
                  </div>

                  {/* Signature */}
                  {showSignature && (
                    <div style={{ textAlign: 'center', minWidth: '150px' }}>
                      {signatureUrl ? (
                        <img src={signatureUrl} alt="Doctor Signature" style={{ maxWidth: '130px', maxHeight: '48px', objectFit: 'contain', marginBottom: '4px' }} />
                      ) : (
                        <div style={{ height: '36px' }} />
                      )}
                      <div style={{ width: '140px', height: '1px', background: '#64748B', margin: '0 auto 4px auto' }} />
                      <div style={{ fontSize: '11.5px', fontWeight: '700', color: '#0F172A' }}>
                        {doctorName.startsWith('Dr.') ? doctorName : `Dr. ${doctorName}`}
                      </div>
                      {doctorQual && <div style={{ fontSize: '10px', color: '#64748B' }}>{doctorQual}</div>}
                    </div>
                  )}
                </div>

                {/* Footer Strip */}
                {showFooter && (
                  <div style={{
                    background: '#F1F5F9',
                    padding: '7px 12px',
                    borderRadius: '4px',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    fontSize: '9.5px',
                    color: '#475569'
                  }}>
                    <div>{clinicName} {clinicPhone}</div>
                    <div>{footerText}</div>
                  </div>
                )}
              </div>
            )}

            {/* CONSENT FOOTER BAR */}
            {docTab === 'consent' && showFooter && (
              <div style={{
                marginTop: '20px',
                background: '#F1F5F9',
                padding: '6px 10px',
                borderRadius: '4px',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                fontSize: '9.5px',
                color: '#475569'
              }}>
                <div>{clinicName} {clinicPhone && `• Contact: ${clinicPhone}`}</div>
                <div>{footerText}</div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
